version: '3.8'

services:
  # Mitmproxy for Altoro Mutual
  mitm-altoro:
    image: mitmproxy/mitmproxy:9.0.1
    container_name: mitm-altoro
    command: mitmdump --mode reverse:http://altoro-mutual:8080/ -s /logs/log_script.py
    environment:
      - LOG_NAME=altoro
    volumes:
      - ./shared-volume:/logs
      - ./mitmproxy/log_script.py:/logs/log_script.py
    ports:
      - "9000:8080"
    networks:
      - redteam
    depends_on:
      - altoro-mutual

  # Mitmproxy for Juice Shop
  mitm-juice:
    image: mitmproxy/mitmproxy:9.0.1
    container_name: mitm-juice
    command: mitmdump --mode reverse:http://juice-shop:3000/ -s /logs/log_script.py
    environment:
      - LOG_NAME=juice
    volumes:
      - ./shared-volume:/logs
      - ./mitmproxy/log_script.py:/logs/log_script.py
    ports:
      - "9001:8080"
    networks:
      - redteam
    depends_on:
      - juice-shop

  # Mitmproxy for DVWA
  mitm-dvwa:
    image: mitmproxy/mitmproxy:9.0.1
    container_name: mitm-dvwa
    command: mitmdump --mode reverse:http://dvwa:80/ -s /logs/log_script.py
    environment:
      - LOG_NAME=dvwa
    volumes:
      - ./shared-volume:/logs
      - ./mitmproxy/log_script.py:/logs/log_script.py
    ports:
      - "9002:8080"
    networks:
      - redteam
    depends_on:
      - dvwa

  altoro-mutual:
    image: eystsen/altoro
    container_name: altoro-mutual
    ports:
      - "8082:8080"
    networks:
      - redteam
    restart: always

  juice-shop:
    image: bkimminich/juice-shop
    container_name: juice-shop
    ports:
      - "3000:3000"
    networks:
      - redteam
    restart: always

  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    environment:
      - MYSQL_PASS=pass
    ports:
      - "8081:80"
    networks:
      - redteam
    restart: always

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.13.4
    container_name: filebeat
    user: root
    network_mode: host
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./shared-volume:/shared-logs:ro
      - ./filebeat/certs:/usr/share/filebeat/certs:ro
    depends_on:
      - mitm-altoro
      - mitm-juice
      - mitm-dvwa
    restart: always
    
networks:
  redteam:
    driver: bridge
